//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities(string conn)
            : base(conn)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBanVe> tblBanVes { get; set; }
        public virtual DbSet<tblContent> tblContents { get; set; }
        public virtual DbSet<tblDongGoi> tblDongGois { get; set; }
        public virtual DbSet<tblInput> tblInputs { get; set; }
        public virtual DbSet<tblKhauIn> tblKhauIns { get; set; }
        public virtual DbSet<tblNgayNghi> tblNgayNghis { get; set; }
        public virtual DbSet<tblQC> tblQCs { get; set; }
        public virtual DbSet<tblQCDetail> tblQCDetails { get; set; }
        public virtual DbSet<tblThoiGianNghi> tblThoiGianNghis { get; set; }
        public virtual DbSet<tblURL> tblURLs { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tblViTriNguoiTT> tblViTriNguoiTTs { get; set; }
        public virtual DbSet<tblWO> tblWOes { get; set; }
        public virtual DbSet<v_01_Kitting> v_01_Kitting { get; set; }
        public virtual DbSet<v_04_DongGoi> v_04_DongGoi { get; set; }
        public virtual DbSet<v_05_KhauDetail> v_05_KhauDetail { get; set; }
        public virtual DbSet<v_05_QCDetail> v_05_QCDetail { get; set; }
        public virtual DbSet<v_06_LoaiSP> v_06_LoaiSP { get; set; }
        public virtual DbSet<v_DSLoaiSP> v_DSLoaiSP { get; set; }
        public virtual DbSet<tblThoiGianKhau> tblThoiGianKhaus { get; set; }
    
        public virtual int pro_01_truncateWO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pro_01_truncateWO");
        }
    
        public virtual ObjectResult<pro_02_tblInputWithTime_Result> pro_02_tblInputWithTime(Nullable<System.DateTime> from, Nullable<System.DateTime> to, string item, string lot)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var itemParameter = item != null ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(string));
    
            var lotParameter = lot != null ?
                new ObjectParameter("lot", lot) :
                new ObjectParameter("lot", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_02_tblInputWithTime_Result>("pro_02_tblInputWithTime", fromParameter, toParameter, itemParameter, lotParameter);
        }
    
        public virtual ObjectResult<pro_03_WOBaoLuu_Result> pro_03_WOBaoLuu(string key_str)
        {
            var key_strParameter = key_str != null ?
                new ObjectParameter("key_str", key_str) :
                new ObjectParameter("key_str", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_03_WOBaoLuu_Result>("pro_03_WOBaoLuu", key_strParameter);
        }
    
        public virtual int pro_04_TruncateBanVe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pro_04_TruncateBanVe");
        }
    
        public virtual int pro_05_TruncateUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pro_05_TruncateUser");
        }
    
        public virtual int pro_06_TruncateViTriNguoiTT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pro_06_TruncateViTriNguoiTT");
        }
    
        public virtual ObjectResult<Nullable<int>> pro_07_TimeOverlapRows(string starthour, string startmin, string endhour, string endmin, string congdoan)
        {
            var starthourParameter = starthour != null ?
                new ObjectParameter("starthour", starthour) :
                new ObjectParameter("starthour", typeof(string));
    
            var startminParameter = startmin != null ?
                new ObjectParameter("startmin", startmin) :
                new ObjectParameter("startmin", typeof(string));
    
            var endhourParameter = endhour != null ?
                new ObjectParameter("endhour", endhour) :
                new ObjectParameter("endhour", typeof(string));
    
            var endminParameter = endmin != null ?
                new ObjectParameter("endmin", endmin) :
                new ObjectParameter("endmin", typeof(string));
    
            var congdoanParameter = congdoan != null ?
                new ObjectParameter("congdoan", congdoan) :
                new ObjectParameter("congdoan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pro_07_TimeOverlapRows", starthourParameter, startminParameter, endhourParameter, endminParameter, congdoanParameter);
        }
    
        public virtual ObjectResult<pro_08_KhauTime_Result> pro_08_KhauTime(Nullable<System.DateTime> from, Nullable<System.DateTime> to, string item, string lot, string manv, string wo, string loaisp)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var itemParameter = item != null ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(string));
    
            var lotParameter = lot != null ?
                new ObjectParameter("lot", lot) :
                new ObjectParameter("lot", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var woParameter = wo != null ?
                new ObjectParameter("wo", wo) :
                new ObjectParameter("wo", typeof(string));
    
            var loaispParameter = loaisp != null ?
                new ObjectParameter("loaisp", loaisp) :
                new ObjectParameter("loaisp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_08_KhauTime_Result>("pro_08_KhauTime", fromParameter, toParameter, itemParameter, lotParameter, manvParameter, woParameter, loaispParameter);
        }
    
        public virtual ObjectResult<pro_09_QCTime_Result> pro_09_QCTime(Nullable<System.DateTime> from, Nullable<System.DateTime> to, string item, string lot, string manv, string wo, string loaisp)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var itemParameter = item != null ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(string));
    
            var lotParameter = lot != null ?
                new ObjectParameter("lot", lot) :
                new ObjectParameter("lot", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var woParameter = wo != null ?
                new ObjectParameter("wo", wo) :
                new ObjectParameter("wo", typeof(string));
    
            var loaispParameter = loaisp != null ?
                new ObjectParameter("loaisp", loaisp) :
                new ObjectParameter("loaisp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_09_QCTime_Result>("pro_09_QCTime", fromParameter, toParameter, itemParameter, lotParameter, manvParameter, woParameter, loaispParameter);
        }
    
        public virtual ObjectResult<pro_10_KittingTime_Result> pro_10_KittingTime(Nullable<System.DateTime> from, Nullable<System.DateTime> to, string item, string lot, string manv, string wo, string loaisp)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var itemParameter = item != null ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(string));
    
            var lotParameter = lot != null ?
                new ObjectParameter("lot", lot) :
                new ObjectParameter("lot", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var woParameter = wo != null ?
                new ObjectParameter("wo", wo) :
                new ObjectParameter("wo", typeof(string));
    
            var loaispParameter = loaisp != null ?
                new ObjectParameter("loaisp", loaisp) :
                new ObjectParameter("loaisp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_10_KittingTime_Result>("pro_10_KittingTime", fromParameter, toParameter, itemParameter, lotParameter, manvParameter, woParameter, loaispParameter);
        }
    
        public virtual ObjectResult<pro_11_DongGoiTime_Result> pro_11_DongGoiTime(Nullable<System.DateTime> from, Nullable<System.DateTime> to, string item, string lot, string manv, string wo, string loaisp)
        {
            var fromParameter = from.HasValue ?
                new ObjectParameter("from", from) :
                new ObjectParameter("from", typeof(System.DateTime));
    
            var toParameter = to.HasValue ?
                new ObjectParameter("to", to) :
                new ObjectParameter("to", typeof(System.DateTime));
    
            var itemParameter = item != null ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(string));
    
            var lotParameter = lot != null ?
                new ObjectParameter("lot", lot) :
                new ObjectParameter("lot", typeof(string));
    
            var manvParameter = manv != null ?
                new ObjectParameter("manv", manv) :
                new ObjectParameter("manv", typeof(string));
    
            var woParameter = wo != null ?
                new ObjectParameter("wo", wo) :
                new ObjectParameter("wo", typeof(string));
    
            var loaispParameter = loaisp != null ?
                new ObjectParameter("loaisp", loaisp) :
                new ObjectParameter("loaisp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_11_DongGoiTime_Result>("pro_11_DongGoiTime", fromParameter, toParameter, itemParameter, lotParameter, manvParameter, woParameter, loaispParameter);
        }
    
        public virtual ObjectResult<pro_12_WOChuaDG_Result> pro_12_WOChuaDG(string key_str)
        {
            var key_strParameter = key_str != null ?
                new ObjectParameter("key_str", key_str) :
                new ObjectParameter("key_str", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_12_WOChuaDG_Result>("pro_12_WOChuaDG", key_strParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> pro_13_getOperationMins(Nullable<System.DateTime> start, Nullable<System.DateTime> end, string loaiSP)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            var loaiSPParameter = loaiSP != null ?
                new ObjectParameter("LoaiSP", loaiSP) :
                new ObjectParameter("LoaiSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pro_13_getOperationMins", startParameter, endParameter, loaiSPParameter);
        }
    
        public virtual ObjectResult<pro_14_TrangThaiSP_Result> pro_14_TrangThaiSP(string loaiSP)
        {
            var loaiSPParameter = loaiSP != null ?
                new ObjectParameter("LoaiSP", loaiSP) :
                new ObjectParameter("LoaiSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_14_TrangThaiSP_Result>("pro_14_TrangThaiSP", loaiSPParameter);
        }
    }
}
