//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDongGoi
    {
        public int id { get; set; }
        public string workorder { get; set; }
        public string WOID { get; set; }
        public Nullable<System.DateTime> Start1 { get; set; }
        public Nullable<System.DateTime> End1 { get; set; }
        public string User1 { get; set; }
        public Nullable<System.DateTime> Start2 { get; set; }
        public Nullable<System.DateTime> End2 { get; set; }
        public string User2 { get; set; }
        public Nullable<System.DateTime> Start3 { get; set; }
        public Nullable<System.DateTime> End3 { get; set; }
        public string User3 { get; set; }
        public Nullable<System.DateTime> Start4 { get; set; }
        public Nullable<System.DateTime> End4 { get; set; }
        public string User4 { get; set; }
        public Nullable<System.DateTime> Start5 { get; set; }
        public Nullable<System.DateTime> End5 { get; set; }
        public string User5 { get; set; }
        public Nullable<System.DateTime> Start6 { get; set; }
        public Nullable<System.DateTime> End6 { get; set; }
        public string User6 { get; set; }
        public Nullable<System.DateTime> Start7 { get; set; }
        public Nullable<System.DateTime> End7 { get; set; }
        public string User7 { get; set; }
        public Nullable<System.DateTime> Start8 { get; set; }
        public Nullable<System.DateTime> End8 { get; set; }
        public string User8 { get; set; }
        public Nullable<System.DateTime> Start9 { get; set; }
        public Nullable<System.DateTime> End9 { get; set; }
        public string User9 { get; set; }
        public Nullable<System.DateTime> Start10 { get; set; }
        public Nullable<System.DateTime> End10 { get; set; }
        public string User10 { get; set; }
        public Nullable<System.DateTime> Start11 { get; set; }
        public Nullable<System.DateTime> End11 { get; set; }
        public string User11 { get; set; }
        public Nullable<System.DateTime> Start12 { get; set; }
        public Nullable<System.DateTime> End12 { get; set; }
        public string User12 { get; set; }
        public Nullable<System.DateTime> Start13 { get; set; }
        public Nullable<System.DateTime> End13 { get; set; }
        public string User13 { get; set; }
        public Nullable<System.DateTime> Start14 { get; set; }
        public Nullable<System.DateTime> End14 { get; set; }
        public string User14 { get; set; }
        public Nullable<System.DateTime> Start15 { get; set; }
        public Nullable<System.DateTime> End15 { get; set; }
        public string User15 { get; set; }
        public Nullable<int> Mins1 { get; set; }
        public Nullable<int> Mins2 { get; set; }
        public Nullable<int> Mins3 { get; set; }
        public Nullable<int> Mins4 { get; set; }
        public Nullable<int> Mins5 { get; set; }
        public Nullable<int> Mins6 { get; set; }
        public Nullable<int> Mins7 { get; set; }
        public Nullable<int> Mins8 { get; set; }
        public Nullable<int> Mins9 { get; set; }
        public Nullable<int> Mins10 { get; set; }
        public Nullable<int> Mins11 { get; set; }
        public Nullable<int> Mins12 { get; set; }
        public Nullable<int> Mins13 { get; set; }
        public Nullable<int> Mins14 { get; set; }
        public Nullable<int> Mins15 { get; set; }
        public Nullable<bool> IsStart { get; set; }
    }
}
