//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQC
    {
        public int id { get; set; }
        public string workorder { get; set; }
        public Nullable<System.DateTime> QCTime_Start { get; set; }
        public Nullable<System.DateTime> QCTime_End { get; set; }
        public string UserQC { get; set; }
        public string WOID { get; set; }
    }
}
