//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblThoiGianNghi
    {
        public int id { get; set; }
        public string CongDoan { get; set; }
        public string BreakStartHour { get; set; }
        public string BreakStartMin { get; set; }
        public string BreakEndHour { get; set; }
        public string BreakEndMin { get; set; }
    }
}
