//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_05_KhauDetail
    {
        public int id { get; set; }
        public string workorder { get; set; }
        public Nullable<System.DateTime> InTime_Start { get; set; }
        public Nullable<System.DateTime> InTime_End { get; set; }
        public string UserIn { get; set; }
        public string WOID { get; set; }
        public string itemnumber { get; set; }
        public string lot { get; set; }
        public string desc1 { get; set; }
        public string desc2 { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<int> OperationMins { get; set; }
        public string userid { get; set; }
        public string name { get; set; }
    }
}
