//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_06_LoaiSP
    {
        public string MES_PART { get; set; }
        public string WORK_ORDER_ID { get; set; }
        public string LoaiSP { get; set; }
    }
}
