//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVS_Manage
    {
        public string Item_Number { get; set; }
        public string UM { get; set; }
        public string Description_1 { get; set; }
        public string Description_2 { get; set; }
        public string Comment { get; set; }
        public string Prod_Line { get; set; }
        public string Item_Type { get; set; }
    }
}
