//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Manage_evsEntities : DbContext
    {
        public Manage_evsEntities(string conn)
            : base(conn)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EVS_Manage> EVS_Manage { get; set; }
        public virtual DbSet<NewInventory_EVS> NewInventory_EVS { get; set; }
    }
}
