//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewInventory_EVS
    {
        public string SITE { get; set; }
        public string loc { get; set; }
        public string Itemcode { get; set; }
        public string LotNo { get; set; }
        public string status { get; set; }
        public Nullable<double> Qty_Allocate { get; set; }
        public Nullable<double> Qty { get; set; }
        public string @ref { get; set; }
        public string um { get; set; }
        public string prod_line { get; set; }
        public string part_type { get; set; }
        public int id { get; set; }
        public string connect_status { get; set; }
    }
}
