//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWO
    {
        public int ID { get; set; }
        public string WORK_ORDER_ID { get; set; }
        public string WORK_ORDER { get; set; }
        public string STATUS { get; set; }
        public string ORDER_DATE { get; set; }
        public string RELEASE_DATE { get; set; }
        public string DUE_DATE { get; set; }
        public string LOCATION_ID { get; set; }
        public string LOT_SERIAL { get; set; }
        public string WO_PART { get; set; }
        public string MES_PART { get; set; }
        public string DESCRIPTION_FOR_WO_PART_EN { get; set; }
        public string DESCRIPTION_FOR_WO_PART_VN { get; set; }
        public string DRAWING_REV { get; set; }
        public string REV { get; set; }
        public string PROD_LINE { get; set; }
        public string ORDER_QTY { get; set; }
        public string COMPLETE_QTY { get; set; }
        public string REJECT_QTY { get; set; }
        public string OPEN_QTY { get; set; }
        public string WO_COMPONENT { get; set; }
        public string MES_COMPONENT { get; set; }
        public string DESCRIPTION_FOR_WO_COMPONENT_EN { get; set; }
        public string DESCRIPTION_FOR_WO_COMPONENT_VN { get; set; }
        public string ITEM_TYPE { get; set; }
        public string LOT_SERIAL_ALLOCATE { get; set; }
        public string REQUIRE_QTY { get; set; }
        public string STORAGE_LOCATION { get; set; }
        public string QTY_ISSUED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    }
}
