//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus.Data_EVS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Manage_evsEntities : DbContext
    {
        public Manage_evsEntities(string conn)
            : base(conn)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EVS_Manage> EVS_Manage { get; set; }
        public virtual DbSet<EVS_Stock> EVS_Stock { get; set; }
        public virtual DbSet<tblWO> tblWOes { get; set; }
        public virtual DbSet<Kitting_Infor> Kitting_Infor { get; set; }
        public virtual DbSet<EVS_Inventory> EVS_Inventory { get; set; }
    
        public virtual int Kitting_Infor_Data()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Kitting_Infor_Data");
        }
    
        public virtual int Update_EVS_Stock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_EVS_Stock");
        }
    
        public virtual int update_tblWO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_tblWO");
        }
    }
}
