//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus.Data_EVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVS_Stock
    {
        public int ID { get; set; }
        public string MATERIAL_CODE { get; set; }
        public string PLANT { get; set; }
        public string BATCH_NUMBER { get; set; }
        public string STORAGE_LOCATION { get; set; }
        public string MATERIAL_TYPE { get; set; }
        public string BASE_UOM { get; set; }
        public string STOCK_TYPE { get; set; }
        public Nullable<decimal> STOCK_QUANTITY { get; set; }
        public string CONNECT_STATUS { get; set; }
    }
}
