//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus.Data_EVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVS_Inventory
    {
        public int id { get; set; }
        public string Storage_Location { get; set; }
        public string Descript_Location { get; set; }
        public string Stock_Type { get; set; }
        public string Material_Number { get; set; }
        public string Registered__Material { get; set; }
        public string Batch_Number { get; set; }
        public string Vendor_Batch_Number { get; set; }
        public string Inventory_Qty { get; set; }
        public string Available_Qty { get; set; }
        public string MRP_Controller { get; set; }
        public string Connect_Status { get; set; }
        public string Eink_Mac { get; set; }
        public string Eink_Variant { get; set; }
    }
}
