//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_Management.Data_EVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitting_Infor
    {
        public int stt { get; set; }
        public string woid { get; set; }
        public string id { get; set; }
        public string com { get; set; }
        public string lot { get; set; }
        public long Nhom_Kitting { get; set; }
        public int quantity { get; set; }
        public string locate_kitting { get; set; }
        public string draw_rev { get; set; }
        public string wo { get; set; }
    }
}
