//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVS_ProductionStatus.Data_EVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packing_List
    {
        public int id { get; set; }
        public Nullable<int> idPL { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public string MaPL { get; set; }
        public string ChungLoai { get; set; }
        public string ThietBi { get; set; }
        public string WO_No { get; set; }
        public string ID_No { get; set; }
        public string Item_No { get; set; }
        public string Rev_No { get; set; }
        public Nullable<int> Qty { get; set; }
        public string ThietBi_Detail { get; set; }
        public string strFull { get; set; }
        public string Result { get; set; }
    }
}
